### ISSUE TITLE
Extra Credit Task

### ISSUE THREAD

**Issue by kirmal-mal** [BoiseState/CS471-Assignments-Workflows#3]
References user story #1

## TODO:
- [x] Create a new PR having the **base** branch `master` and the **compare** branch `task-6_squash_preferred_project_workflow`
- [x] Create new branch `extra_credit`
- [x] Create 3 commits
- [x] Create PR for this branch
- [x] Delete branch after PR succesful
